// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using modulo6api.Context;

#nullable disable

namespace modulo6api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110013329_primeiro")]
    partial class primeiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("modulo6api.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCliente"), 1L, 1);

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("dataNasc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("modulo6api.Models.Compra", b =>
                {
                    b.Property<int>("idCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCompra"), 1L, 1);

                    b.Property<int?>("clienteidCliente")
                        .HasColumnType("int");

                    b.Property<string>("formaPgto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idPassagem")
                        .HasColumnType("int");

                    b.Property<int?>("passagemidPassagem")
                        .HasColumnType("int");

                    b.Property<double>("valorTotal")
                        .HasColumnType("float");

                    b.HasKey("idCompra");

                    b.HasIndex("clienteidCliente");

                    b.HasIndex("passagemidPassagem");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("modulo6api.Models.Passagem", b =>
                {
                    b.Property<int>("idPassagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPassagem"), 1L, 1);

                    b.Property<string>("ciaAerea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("idPassagem");

                    b.ToTable("Passagem");
                });

            modelBuilder.Entity("modulo6api.Models.Compra", b =>
                {
                    b.HasOne("modulo6api.Models.Cliente", "cliente")
                        .WithMany("compra")
                        .HasForeignKey("clienteidCliente");

                    b.HasOne("modulo6api.Models.Passagem", "passagem")
                        .WithMany("compra")
                        .HasForeignKey("passagemidPassagem");

                    b.Navigation("cliente");

                    b.Navigation("passagem");
                });

            modelBuilder.Entity("modulo6api.Models.Cliente", b =>
                {
                    b.Navigation("compra");
                });

            modelBuilder.Entity("modulo6api.Models.Passagem", b =>
                {
                    b.Navigation("compra");
                });
#pragma warning restore 612, 618
        }
    }
}
